name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore linux-x64
      run: dotnet restore -r linux-x64
    - name: Publish linux-x64
      run: dotnet publish -c Release --self-contained -r linux-x64 -o release-linux
    - name: Archive linux-x64 build
      uses: ihiroky/archive-action@v1
      with:
        root_dir: release-linux
        file_path: OrbisDbTools_linux_${{ GITHUB_SHA::8 }}.tar.xz
    - name: Upload artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        path: OrbisDbTools_linux_${{ GITHUB_SHA::8 }}.tar.xz