name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Nuget Restore
      run: dotnet restore
      
    - name: Publish linux-x64
      run: dotnet publish -c Release --self-contained -r linux-x64 -o release-linux
    - name: Publish win-x64
      run: dotnet publish -c Release --self-contained -r win-x64 -o release-win64
    - name: Publish osx-x64
      run: dotnet publish -c Release --self-contained -r osx-x64 -o release-osx_x64

    - name: Archive linux-x64 build
      uses: ihiroky/archive-action@v1
      with:
        root_dir: release-linux
        file_path: OrbisDbTools_linux.tar.xz

    - name: Archive win64-x64 build
      uses: ihiroky/archive-action@v1
      with:
        root_dir: release-win64
        file_path: OrbisDbTools_win64.tar.xz

    - name: Archive osx_x64 build
      uses: ihiroky/archive-action@v1
      with:
        root_dir: release-osx_x64
        file_path: OrbisDbTools_osx_x64.tar.xz

    - name: Upload linux-x64
      uses: actions/upload-artifact@v2.3.1
      with:
        name: linux-x64
        path: OrbisDbTools_linux.tar.xz

    - name: Upload win-x64
      uses: actions/upload-artifact@v2.3.1
      with:
        name: win-x64
        path: OrbisDbTools_win64.tar.xz

    - name: Upload osx-x64
      uses: actions/upload-artifact@v2.3.1
      with:
        name: osx-x64
        path: OrbisDbTools_osx_x64.tar.xz